# Generated by Django 5.1.2 on 2024-12-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('created_at',)},
        ),
    ]
