# Generated by Django 5.1.2 on 2024-12-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_at',)},
        ),
    ]
